// <auto-generated />
using CorePlugin.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorePlugin.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20260129111128_coreplugin-inital")]
    partial class coreplugininital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CorePlugin.EF.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("card_id")
                        .IsFixedLength();

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("card_no")
                        .IsFixedLength();

                    b.Property<int>("Paseli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(10000)
                        .HasColumnName("paseli");

                    b.Property<string>("PaseliSession")
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("paseli_session")
                        .IsFixedLength();

                    b.Property<string>("PassCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("pass")
                        .IsFixedLength();

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("ref_id")
                        .IsFixedLength()
                        .HasComment("same with dataid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("card", null, t =>
                        {
                            t.HasComment("Stores e-amusement cards");
                        });
                });

            modelBuilder.Entity("CorePlugin.EF.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<string>("CountryJName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_jname");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_name");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("facility_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PCBId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pcb_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region");

                    b.Property<string>("RegionJName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region_jname");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region_name");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("facility", null, t =>
                        {
                            t.HasComment("Stores facility");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
