<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <EnableDefaultRazorItems>false</EnableDefaultRazorItems>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Views/**/*.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CorePlugin\CorePlugin.csproj" />
    <ProjectReference Include="..\Stella.Abstractions\Stella.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="plugin_kfc.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="Data/Seed/asphyxia_data.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data/Seed/events_list.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data/Seed/startup_flags.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<PluginFiles Include="$(TargetDir)$(ProjectName).dll" />
			<PluginFiles Include="$(TargetDir)plugin_kfc.json" />
		</ItemGroup>
		<Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(SolutionDir)Stella/bin/Debug/net10.0/plugins/" SkipUnchangedFiles="true" />
		<ItemGroup>
			<SeedFiles Include="$(TargetDir)Data/Seed/asphyxia_data.json" />
			<SeedFiles Include="$(TargetDir)Data/Seed/events_list.json" />
			<SeedFiles Include="$(TargetDir)Data/Seed/startup_flags.json" />
		</ItemGroup>
		<Copy SourceFiles="@(SeedFiles)" DestinationFolder="$(SolutionDir)Stella/bin/Debug/net10.0/Data/Seed/" SkipUnchangedFiles="true" />
	</Target>
</Project>
